api:
  base_url: "https://api.ouraring.com/v2"
  token: "${OURA_API_TOKEN}"
  endpoints:
    sleep: "/usercollection/sleep"
    activity: "/usercollection/daily_activity"
    readiness: "/usercollection/daily_readiness"

gcp:
  # Read from Terraform output files
  bucket_name: "${data.terraform_remote_state.oura.outputs.bucket_name}"
  dataset_id: "${data.terraform_remote_state.oura.outputs.dataset_id}"
  location: "${data.terraform_remote_state.oura.outputs.location}"
  project_id: "${data.terraform_remote_state.oura.outputs.project_id}"
  
  # GCS paths
  raw_data_path_str: "raw/oura/{data_type}/{start_date}_{end_date}"
