steps:
# Install dependencies
- name: 'python:3.9'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt', '-t', '.']

# Run tests
- name: 'python:3.9'
  entrypoint: python
  args: ['-m', 'pytest', 'tests/', '--junitxml=test-reports/junit.xml']
  env:
    - 'PYTHONPATH=/workspace'

# Run linting
- name: 'python:3.9'
  entrypoint: bash
  args: ['./scripts/lint.sh']

# Save commit SHA for debugging
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'echo $COMMIT_SHA > REVISION.txt'

# Deploy DAGs to Cloud Composer
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'composer_dags/dags'
    - '${_COMPOSER_BUCKET}/dags'

timeout: '1800s'  # 30 minutes

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _COMPOSER_BUCKET: '' # Will be provided by Cloud Build trigger

artifacts:
  reports:
    junit_xml: test-reports/junit.xml
